### ISSUE TITLE
Why do we need segmentation

### ISSUE THREAD

**Issue by Taekyoon** [NVIDIA/waveglow#156]
I just found the code in `mel2samp.py`.

In the code line there says,

```python
class Mel2Samp(torch.utils.data.Dataset):
        .......
        if audio.size(0) >= self.segment_length:
            max_audio_start = audio.size(0) - self.segment_length
            audio_start = random.randint(0, max_audio_start)
            audio = audio[audio_start:audio_start + self.segment_length]
        .......
```
I just wonder why do we segment from an audio file, not just whole audio?
I read this paper to find the reason, but I couldn't find yet.
Does anyone know about this? 

Thanks.

**Comment by jongwook** [comment]
To keep the memory and computation requirement for computing a batch under a certain limit. It also assures that many different files are in a batch assuing the diversity (generally good for training), rather than having one utterance. I suppose 16000 samples is a good hyperparameter the authors have found, but for sure you can experiment with it.

**Comment by Taekyoon** [comment]
I think the answer by @jongwook will be helpful. So, now I close this issue.
